Feature/22 fix process update
fga-eps-mds/2023-2-CAPJu-ProcessManagement-Service pull request #10
Opened 2023-10-22 21:53 UTC by JongaMatos

## Issue

https://github.com/fga-eps-mds/2023-2-CAPJu-Doc/issues/22)
## Descrição
Neste PR se encontram as modificações necessárias para adicionar as modificações da issue no front, então existe um segundo PR, no repositorio do front.

As mudanças são:

- Adiciona um filtro para processos que recebe um array dos status que devem ser buscados.
- Adiciona um filtro para buscar processos cuja effectiveDate se encontre entre as datas `from` e `to`.

## Revisão

Conferir se os filtros estão funcionando devidamente. (eles se encontram na rota base de processos).

Obs: recomendo revisar em conjunto com o pr do front.

2023-10-23 01:00 UTC, WashingtonBispo requested changes
O comando docker-compose up não funciona. Ele não consegue encontrar o entrypoint

![image](https://github.com/fga-eps-mds/2023-2-CAPJu-ProcessManagement-Service/assets/43673797/9572247a-6a12-4471-8a18-31f6003cbf36)

2023-10-23 02:27 UTC, WashingtonBispo approved these changes
Funcionou corretamente de acordo com o protótipo

2023-10-27 22:33 UTC, brendavsantos approved these changes

2023-10-27 23:06 UTC, WashingtonBispo approved these changes
ldtm

2023-10-28 00:28 UTC, merged